baseurl = "http://jrusev.github.io/"
languageCode = "en-us"
title = "JR's tech blog"
theme = "hugo-steam-theme"
# disqusShortname = ""
paginate = 3

[params]

  title = "JR's Tech Blog"
  subtitle = "bits of thoughts"
  copyright = "" # "All rights reserved."

  # You can choose between green, orange, red and blue.
  themeColor = "green"
  # Enable Google Analytics by inserting your tracking code
  googleAnalytics = ""

  # To provide some metadata for search engines and the about section in the footer
  # feel free to add a few information about you and your website.
  name = "Jivko Rusev"
  bio = "Software engineer"
  description = "Sharing my thoughts on technology"
  location = "" # optional
  twitter = "JivkoRusev" # optional
  github = "jrusev" # optional
  facebook = "jkrusev" # optional
  linkedin = "jrusev" # optional

  # Enable a comment system
  # You can choose between Disqus or Google Plus by setting comments
  # to disqus or googleplus. For using Disqus you need to enter your
  # shortname in disqusShortname at the top of the configs.
  # comments = "disqus"

  # Customize or translate the strings
  keepReadingStr = "Keep reading"
  backtotopStr = "Back to top"
  shareStr = "Share"
  pageNotFoundTitle = "404 - Page not found"
